In [10]:
import numpy as np
import scipy 
import scipy.io.wavfile
import scipy.signal
import os
import zipfile

In [126]:
fs,y = scipy.io.wavfile.read('Python/padpy1516/wav_samples/Snare-Drum-6.wav')
y = np.mean(y,axis=1)

In [122]:
n, = np.shape(y)
fs

44100

In [63]:
fs,y2 = scipy.io.wavfile.read('../padpy1516/wav_samples/Closed-Hi-Hat-3.wav')
y2 = np.mean(y2,axis=1)
fs

44100

In [124]:
y[:6092] = 0.5*y[:6092]+ 0.5*y2

In [130]:
scipy.io.wavfile.write('test.wav',
                       fs,
                       np.int16(y/max(np.abs(y))*32767))


In [148]:
# read song
f = open('song.txt', 'r')
l = ["track" + line[:2] + ".txt" for line in f]

array(['track01.txt', 'track02.txt', 'track03.txt'], 
      dtype='<U11')

In [2]:
# read song
f = open('utwor1/track01.txt', 'r')
l = np.array([line.split() for line in f])
l

array([['01', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '--'],
       ['--', '--', '03', '--'],
       ['01', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '--'],
       ['--', '--', '03', '--'],
       ['01', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['01', '02', '03', '04'],
       ['--', '--', '03', '04'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '04']], 
      dtype='<U2')

In [3]:
n, m = np.shape(l)

In [4]:
s = np.unique(l)
s = s[s != "--"]
s

array(['01', '02', '03', '04'], 
      dtype='<U2')

In [6]:
for si in s:
    fs,y = scipy.io.wavfile.read("utwor1/sample"+si + ".wav")
    y = np.mean(y,axis=1)

c:\Anaconda3\lib\site-packages\scipy\io\wavfile.py:179: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


In [60]:
import os
sample = [f for f in os.listdir("utwor1") if f.endswith(".wav")]
sample

['sample01.wav', 'sample02.wav', 'sample03.wav', 'sample04.wav']

In [9]:
l = [scipy.io.wavfile.read("utwor1/"+si)[1] for si in sample]
l

c:\Anaconda3\lib\site-packages\scipy\io\wavfile.py:179: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


[array([[ 20,  19],
        [ -9, -12],
        [-52, -49],
        ..., 
        [ 41,  45],
        [ 41,  60],
        [-18, -15]], dtype=int16), array([[  3,   7],
        [  7,   2],
        [  4,   2],
        ..., 
        [ 39, -11],
        [-26, -11],
        [  8,  14]], dtype=int16), array([[  2,   2],
        [  0,   2],
        [ -2,  -2],
        ..., 
        [-19, -12],
        [-17,   0],
        [ -9,   2]], dtype=int16), array([[ 0,  0],
        [ 0, -1],
        [-1,  0],
        ..., 
        [ 0, -1],
        [-1,  1],
        [ 1,  0]], dtype=int16)]

In [61]:
# slownik z samplami ich rozmiarem 
samples_dict = {}
for si in sample:
    x = scipy.io.wavfile.read("utwor1/"+si)[1]
    samples_dict[si[6:8]] = np.mean(x,axis=1), np.shape(x)[0]
samples_dict.values()

c:\Anaconda3\lib\site-packages\scipy\io\wavfile.py:179: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)


dict_values([(array([ 19.5, -10.5, -50.5, ...,  43. ,  50.5, -16.5]), 11297), (array([  5. ,   4.5,   3. , ...,  14. , -18.5,  11. ]), 6313), (array([ -0.5,   1. ,   2. , ...,  29.5,  14.5,   0. ]), 705557), (array([  10. ,   58. ,  149. , ...,   34.5,   27. ,   15. ]), 50406)])

In [19]:
samples_dict["01"]

(array([ 19.5, -10.5, -50.5, ...,  43. ,  50.5, -16.5]), 11297)

In [54]:
samples_dict.values()

dict_values([])

In [50]:
# read track
f = open('utwor1/track01.txt', 'r')
l = np.array([line.split() for line in f])
l

array([['01', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '--'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '--'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '04'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '--'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '--'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '--'],
       ['--', '02', '03', '04'],
       ['--', '--', '03', '04'],
       ['--', '02', '03', '04'],
       ['-

In [58]:
T = 20
fs = 44100 
z = np.zeros(T*fs)
ni = np.zeros(4)
for i in range(4):
    for j in range(len(l)):
        if l[j, i] != '--':
            z[ni[i]:(ni[i]+samples_dict[l[j,i]][1])] += 0.25 * samples_dict[l[j,i]][0]
        ni[i] += fs/2

c:\Anaconda3\lib\site-packages\ipykernel\__main__.py:8: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [50]:
scipy.io.wavfile.write('test.wav',
                       fs,
                       np.int16(z/max(np.abs(z))*32767))


In [106]:
samples_dict.values()

dict_values([(array([[ 0,  0],
       [ 0, -1],
       [-1,  0],
       ..., 
       [ 0, -1],
       [-1,  1],
       [ 1,  0]], dtype=int16), (15221, 2)), (array([[  2,   2],
       [  0,   2],
       [ -2,  -2],
       ..., 
       [-19, -12],
       [-17,   0],
       [ -9,   2]], dtype=int16), (9594, 2)), (array([[  3,   7],
       [  7,   2],
       [  4,   2],
       ..., 
       [ 39, -11],
       [-26, -11],
       [  8,  14]], dtype=int16), (6313, 2)), (array([[ 20,  19],
       [ -9, -12],
       [-52, -49],
       ..., 
       [ 41,  45],
       [ 41,  60],
       [-18, -15]], dtype=int16), (11297, 2))])

In [103]:
ni

array([ 11297.,  12626.,  38376.,  15221.])

In [98]:
l[1, 0] != '01'

True

In [140]:
f = "track01.txt"
f.find("track")>=0

True

In [143]:
[f for f in os.listdir("utwor1") if f.find("track")>=0]

['track01.txt']

In [1]:
t = "track01.txt" 
t[5:7]

'01'

In [7]:
s = open('utwor1/defs.txt', 'r').read()
defs = eval(s)
defs.keys()

dict_keys(['bpm'])

## zip file

In [1]:
import zipfile

In [20]:
zipfile.is_zipfile("utwor2.zip")

True

In [12]:
songzip = zipfile.ZipFile('utwor2.zip')

In [17]:
songzip.extractall("temp")

<zipfile.ZipFile filename='utwor2.zip' mode='r'>

## instrument 

In [114]:
def dzwiek(f, T, a, d):
    fs = 44100 # Hz, sampling frequency
    t = np.linspace(0, T, T*fs)
    y = np.sin(2*np.pi*f*t+0.1)#+0.15*scipy.signal.sawtooth(2*np.pi*f*t)
#     y[0:int(T*fs*a)] *= np.linspace(0,1,int(T*fs*a))
#     y[-int(T*fs*d):-1] *= np.linspace(1,0,int(T*fs*d)-1)
    return y

S = pow(2, 1/12)
fs = 44100
import scipy.io.wavfile
y = np.r_[dzwiek(440*S**(-2), 0.5, 0.2, 0.4),
          dzwiek(440*S**(-5), 0.5, 0.2, 0.4),
          dzwiek(440*S**(-5), 0.5, 0.2, 0.4)]
scipy.io.wavfile.write('test2.wav',
                       fs,
                       np.int16(y/max(np.abs(y))*32767))

NameError: name 'f' is not defined

466.1637615180899

In [125]:
S = pow(2, 1/12)
fs = 44100
m = ["C-", "C#", "D-", "D#", "E-", "F-", "F#", "G-", "G#", "A-", "A#", "B-"]
f = [440*S**(i-9) for i in range(12)]
inst = {m[i]:f[i] for i in range(len(m))}
inst

{'A#': 466.1637615180899,
 'A-': 440.0,
 'B-': 493.8833012561241,
 'C#': 277.182630976872,
 'C-': 261.6255653005985,
 'D#': 311.1269837220808,
 'D-': 293.66476791740746,
 'E-': 329.62755691286986,
 'F#': 369.99442271163434,
 'F-': 349.2282314330038,
 'G#': 415.3046975799451,
 'G-': 391.99543598174927}

In [119]:
f = open('utwor1/nutki.txt', 'r')
l = np.array([line[0:3] for line in f])
l

array(['G-4', 'E-4', 'E-4', 'F-4', 'D-4', 'D-4', 'C-4', 'E-4', 'G-4',
       '---', 'G-4', 'E-4', 'E-4', 'F-4', 'D-4', 'D-4', 'C-4', 'E-4', 'C-4'], 
      dtype='<U3')

In [129]:
fs = 44100 # Hz, sampling frequency
T = .5
t = np.linspace(0, T, T*fs)
y = []
for i in range(len(l)):
    if l[i] == "---":
        y = np.zeros(int(fs*T))
    else:
        y = np.r_[y, np.sign(np.sin(2*np.pi*inst[l[i][0:2]]*t))]
y

array([ 0.,  0.,  0., ..., -1., -1., -1.])

In [125]:
scipy.io.wavfile.write('test3.wav',
                       fs,
                       np.int16(y/max(np.abs(y))*32767))

array(['G-4', 'E-4', 'E-4', 'F-4', 'D-4', 'D-4', 'C-4', 'E-4', 'G-4',
       'G-4', 'E-4', 'E-4', 'F-4', 'D-4', 'D-4', 'C-4', 'E-4', 'C-4'], 
      dtype='<U3')

In [49]:
s = open('utwor1/defs.txt', 'r').read()
defs = eval(s)
defs["bpm"]

120

### create_song

In [239]:
def create_song(song):
    
    if os.path.exists(song):
        song_path = song + "/"
    elif zipfile.is_zipfile(song + ".zip"):
        song_zip = zipfile.ZipFile(song + '.zip')
        song_zip.extractall("temp")
        song_path = "temp/" + song + "/"
    else:
        return "There's no such song definition"
    defs = open(song_path + '/defs.txt', 'r').read()
    defs = eval(defs)
    
    sample = [f for f in os.listdir(song_path) if f.endswith(".wav")]
    samples_dict = {}
    for si in sample:
        x = scipy.io.wavfile.read(song_path+si)[1]
        x = np.mean(x,axis=1)
        samples_dict[si[6:8]] = x/max(np.abs(x)), np.shape(x)[0]
    

    
    tracks = [f for f in os.listdir(song_path) if f.find("track")>=0]
    tracks_dict = {}
    for t in tracks:
        x = create_track(song_path + t, defs, samples_dict) 
        tracks_dict[t[5:7]] = x 


    f_song = open(song_path + '/song.txt', 'r')
    t = np.array([line for line in f_song])
    y = np.array([])
    for tr in t:
        y = np.r_[y, tracks_dict[tr[0:2]]]
        
    scipy.io.wavfile.write(song + '.wav',
                       44100,
                       np.int16(y/max(np.abs(y))*32767))

In [117]:
create_song("utwor1")
# create_song("utwor2")

15.5
15.5
15.5
01

01

01

02

01

01

03



c:\Anaconda3\lib\site-packages\scipy\io\wavfile.py:179: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)
c:\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
c:\Anaconda3\lib\site-packages\ipykernel\__main__.py:19: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


### create_track

In [233]:
def create_track(track, defs, samples_dict):
    """
    
    """
    f = open(track, 'r')
    track_matrix = np.array([line.split() for line in f])
    T = len(track_matrix)*60/defs['bpm']
    fs = 44100 
    m = T*fs
    z = np.zeros(m)
    t1 = 60/defs['bpm']
    t = np.linspace(0, t1, t1*fs)
    n = 0
    for i in range(len(track_matrix)):
        for j in range(len(track_matrix[i])):
            temp = track_matrix[i, j]
            if len(temp) == 2:
                if temp != '--':
                    n_s = samples_dict[temp][1]
                    if (n + n_s > len(z)):
                        n_s = m - n
                    z[n:(n + n_s)] += 0.5 * samples_dict[temp][0][:n_s]
            elif len(temp) == 3:
                n_s = fs*t1
                if  temp != "---":
                    z[n:(n + n_s)] += np.sin(2*np.pi*inst[temp[0:2]]*2**(int(temp[2])-4)*t)
        n += fs*60/defs['bpm']
    print(z)
    return z

In [229]:
create_track("utwor1/track01.txt", defs)

TypeError: create_track() missing 1 required positional argument: 'samples_dict'

In [240]:
create_song("Szla dzieweczka")

c:\Anaconda3\lib\site-packages\scipy\io\wavfile.py:179: WavFileWarning: Chunk (non-data) not understood, skipping it.
  WavFileWarning)
c:\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


[ 0.          0.04973775  0.09935239 ...,  0.99440539  0.99938099
  0.99941206]
[  4.20195229e-05   3.88148139e-05  -2.92367786e-04 ...,   9.73717943e-01
   9.77658334e-01   9.77720171e-01]


c:\Anaconda3\lib\site-packages\ipykernel\__main__.py:26: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
c:\Anaconda3\lib\site-packages\ipykernel\__main__.py:22: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
